# Generated by Django 3.2 on 2023-04-15 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now=True, null=True, verbose_name='Updated')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='area')),
                ('perimeter', models.FloatField(blank=True, null=True, verbose_name='perimeter')),
                ('ability', models.FloatField(blank=True, null=True, verbose_name='ability')),
                ('wilting_point', models.FloatField(blank=True, null=True, verbose_name='wilting_point')),
                ('used_water', models.FloatField(blank=True, editable=False, null=True, verbose_name='Used Water')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_byplantations_ground_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Ground',
                'verbose_name_plural': 'Grounds',
            },
        ),
        migrations.CreateModel(
            name='State_Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_humedity', models.FloatField(verbose_name='Air Humedity')),
                ('temperature_c', models.FloatField(verbose_name='Temperature celcius')),
                ('temperature_f', models.FloatField(verbose_name='Temperature Fahrenheit')),
                ('ground_humedity', models.FloatField(verbose_name='ground Humedity')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantations.ground')),
            ],
            options={
                'verbose_name': 'State_Ground',
                'verbose_name_plural': 'State_Grounds',
            },
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now=True, null=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('decription', models.TextField(verbose_name='Description')),
                ('duration', models.DateTimeField(verbose_name='Durtation')),
                ('function_Kc', models.FloatField(verbose_name='Crop Coefficient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_byplantations_plantation_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_byplantations_plantation_related', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Plantation',
                'verbose_name_plural': 'Plantations',
            },
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantations.ground')),
            ],
            options={
                'verbose_name': 'Irrigation',
                'verbose_name_plural': 'Irrigations',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlantation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(blank=True, editable=False, null=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('decription', models.TextField(verbose_name='Description')),
                ('duration', models.DateTimeField(verbose_name='Durtation')),
                ('function_Kc', models.FloatField(verbose_name='Crop Coefficient')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'historical Plantation',
                'verbose_name_plural': 'historical Plantations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGround',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(blank=True, editable=False, null=True, verbose_name='Updated')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='area')),
                ('perimeter', models.FloatField(blank=True, null=True, verbose_name='perimeter')),
                ('ability', models.FloatField(blank=True, null=True, verbose_name='ability')),
                ('wilting_point', models.FloatField(blank=True, null=True, verbose_name='wilting_point')),
                ('used_water', models.FloatField(blank=True, editable=False, null=True, verbose_name='Used Water')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plantation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plantations.plantation')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'historical Ground',
                'verbose_name_plural': 'historical Grounds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='ground',
            name='plantation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantations.plantation'),
        ),
        migrations.AddField(
            model_name='ground',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_byplantations_ground_related', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
