# Generated by Django 3.2 on 2023-04-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='thscm',
            field=models.CharField(blank=True, help_text='Temperature and humidity sensor control module', max_length=256, null=True, verbose_name='THSCM'),
        ),
        migrations.AddField(
            model_name='historicalground',
            name='thscm',
            field=models.CharField(blank=True, help_text='Temperature and humidity sensor control module', max_length=256, null=True, verbose_name='THSCM'),
        ),
    ]
