# Generated by Django 4.2.1 on 2023-05-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_irrigation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
