# Generated by Django 4.2.1 on 2023-05-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0002_state_irrigation_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state_irrigation',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='historicalirrigation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
