# Generated by Django 3.2 on 2023-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0002_auto_20230415_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplantation',
            name='used_water',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Used Water'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='used_water',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Used Water'),
        ),
    ]
