# Generated by Django 3.2 on 2023-04-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0003_auto_20230415_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplantation',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantation',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ground',
            name='thscm',
            field=models.CharField(blank=True, help_text='Identifer Number Temperature and humidity sensor control module', max_length=256, null=True, verbose_name='THSCM'),
        ),
        migrations.AlterField(
            model_name='historicalground',
            name='thscm',
            field=models.CharField(blank=True, help_text='Identifer Number Temperature and humidity sensor control module', max_length=256, null=True, verbose_name='THSCM'),
        ),
    ]
