# Generated by Django 4.2.1 on 2023-05-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0003_remove_state_irrigation_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalirrigation',
            name='on_irrigation',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='on_irrigation',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='historicalirrigation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
