# Generated by Django 3.2 on 2023-04-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0004_auto_20230416_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalplantation',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='plantation',
            old_name='decription',
            new_name='description',
        ),
    ]
