# Generated by Django 4.2.1 on 2023-05-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0005_alter_historicalirrigation_on_irrigation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalirrigation',
            name='on_irrigation',
            field=models.BooleanField(default=False, verbose_name='On Irrigation'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='on_irrigation',
            field=models.BooleanField(default=False, verbose_name='On Irrigation'),
        ),
    ]
