# Generated by Django 3.2 on 2023-04-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0006_auto_20230416_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplantation',
            name='function_Kc',
            field=models.FloatField(blank=True, null=True, verbose_name='Crop Coefficient'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='function_Kc',
            field=models.FloatField(blank=True, null=True, verbose_name='Crop Coefficient'),
        ),
    ]
