# Generated by Django 4.2.1 on 2023-05-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0007_alter_state_irrigation_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_irrigation',
            name='water_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
