# Generated by Django 4.2 on 2023-05-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0008_alter_state_irrigation_water_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_irrigation',
            name='water_quantity',
            field=models.FloatField(),
        ),
    ]
