# Generated by Django 3.2 on 2023-04-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0008_auto_20230416_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplantation',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='Enter the duration of the crop in days to process the calculation of the estimated date', verbose_name='Durtation'),
        ),
        migrations.AlterField(
            model_name='historicalplantation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='Enter the duration of the crop in days to process the calculation of the estimated date', verbose_name='Durtation'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
