# Generated by Django 3.2 on 2023-04-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0009_auto_20230416_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='historicalground',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
