# Generated by Django 4.2 on 2023-05-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0009_alter_state_irrigation_water_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplantation',
            name='thscm',
            field=models.CharField(blank=True, db_index=True, help_text='Identifer Number Temperature and humidity sensor control module', max_length=256, null=True, verbose_name='THSCM'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='thscm',
            field=models.CharField(blank=True, help_text='Identifer Number Temperature and humidity sensor control module', max_length=256, null=True, unique=True, verbose_name='THSCM'),
        ),
    ]
