# Generated by Django 3.2 on 2023-04-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0010_auto_20230416_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='ability',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ability'),
        ),
        migrations.AlterField(
            model_name='ground',
            name='area',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='ground',
            name='perimeter',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='perimeter'),
        ),
        migrations.AlterField(
            model_name='ground',
            name='wilting_point',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='wilting_point'),
        ),
        migrations.AlterField(
            model_name='historicalground',
            name='ability',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ability'),
        ),
        migrations.AlterField(
            model_name='historicalground',
            name='area',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='historicalground',
            name='perimeter',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='perimeter'),
        ),
        migrations.AlterField(
            model_name='historicalground',
            name='wilting_point',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='wilting_point'),
        ),
    ]
