# Generated by Django 3.2 on 2023-04-16 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0011_auto_20230416_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='plantation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_ground', to='plantations.plantation'),
        ),
    ]
