# Generated by Django 4.2.1 on 2023-05-29 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0011_state_irrigation_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state_irrigation',
            name='created',
        ),
    ]
