# Generated by Django 4.2.1 on 2023-05-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0012_remove_state_irrigation_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_irrigation',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
