# Generated by Django 4.2.1 on 2023-05-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0013_state_irrigation_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_irrigation',
            name='duration',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
