# Generated by Django 3.2 on 2023-04-16 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0013_auto_20230416_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigation',
            name='ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation', to='plantations.ground'),
        ),
    ]
