# Generated by Django 3.2 on 2023-04-16 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0014_alter_irrigation_ground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_ground',
            name='ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_state', to='plantations.ground'),
        ),
    ]
