# Generated by Django 4.2.1 on 2023-05-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0014_alter_state_irrigation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_irrigation',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duartion'),
        ),
    ]
