# Generated by Django 4.2 on 2023-04-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0018_alter_historicalirrigation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalirrigation',
            name='ground',
        ),
        migrations.RemoveField(
            model_name='irrigation',
            name='ground',
        ),
        migrations.RemoveField(
            model_name='state_ground',
            name='ground',
        ),
        migrations.AddField(
            model_name='historicalirrigation',
            name='plantation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plantations.plantation'),
        ),
        migrations.AddField(
            model_name='historicalplantation',
            name='ability',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ability'),
        ),
        migrations.AddField(
            model_name='historicalplantation',
            name='area',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='historicalplantation',
            name='perimeter',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='perimeter'),
        ),
        migrations.AddField(
            model_name='historicalplantation',
            name='thscm',
            field=models.CharField(blank=True, help_text='Identifer Number Temperature and humidity sensor control module', max_length=256, null=True, verbose_name='THSCM'),
        ),
        migrations.AddField(
            model_name='historicalplantation',
            name='wilting_point',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='wilting_point'),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='plantation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation', to='plantations.plantation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantation',
            name='ability',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ability'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='area',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='perimeter',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='perimeter'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='thscm',
            field=models.CharField(blank=True, help_text='Identifer Number Temperature and humidity sensor control module', max_length=256, null=True, verbose_name='THSCM'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='wilting_point',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='wilting_point'),
        ),
        migrations.AddField(
            model_name='state_ground',
            name='plantation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ground_state', to='plantations.plantation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalirrigation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalplantation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalplantation',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nombre'),
        ),
    ]
