# Generated by Django 4.2 on 2023-04-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0019_remove_historicalirrigation_ground_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalground',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalground',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalground',
            name='plantation',
        ),
        migrations.RemoveField(
            model_name='historicalground',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Ground',
        ),
        migrations.DeleteModel(
            name='HistoricalGround',
        ),
    ]
