# Generated by Django 4.2 on 2023-05-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0020_remove_historicalground_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplantation',
            name='ability',
            field=models.FloatField(blank=True, null=True, verbose_name='ability'),
        ),
        migrations.AlterField(
            model_name='historicalplantation',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='historicalplantation',
            name='perimeter',
            field=models.FloatField(blank=True, null=True, verbose_name='perimeter'),
        ),
        migrations.AlterField(
            model_name='historicalplantation',
            name='wilting_point',
            field=models.FloatField(blank=True, null=True, verbose_name='wilting_point'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='ability',
            field=models.FloatField(blank=True, null=True, verbose_name='ability'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='perimeter',
            field=models.FloatField(blank=True, null=True, verbose_name='perimeter'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='wilting_point',
            field=models.FloatField(blank=True, null=True, verbose_name='wilting_point'),
        ),
    ]
