import { useAuthContext } from "../../hooks/useAuthContext";

const index = () => {
  return (
    <div className="styles dashboardContainer">
      <h2>Dashboard</h2>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia magni tempore sit perferendis est quibusdam consectetur alias esse assumenda aut aliquid cupiditate, amet impedit similique veritatis aliquam quaerat sint omnis aperiam accusantium quasi excepturi? <br /> Consectetur iure fugiat eius quia at sit ea hic officiis labore eligendi! Earum facere libero dicta, mollitia voluptates ipsum, sequi deserunt quos sunt eos voluptate. Perspiciatis deserunt magnam exercitationem! Accusantium totam sapiente ipsum eveniet iste facilis delectus optio quas. Quam, obcaecati? Placeat consectetur earum ab quasi laborum nisi consequatur sunt soluta eligendi libero provident <br /> eaque ut, aliquid necessitatibus sed molestias? Incidunt nemo consequatur, quidem tempora quae animi esse maxime eos quam officia minima voluptatibus, deserunt vitae! Consequatur deserunt quae pariatur. Consequatur quasi eveniet incidunt cum laudantium vero, pariatur molestias omnis vitae amet asperiores quaerat perspiciatis libero exercitationem fugiat illum dolorum nisi. Obcaecati deserunt necessitatibus ratione veniam eos in? Modi consequatur impedit <br /> blanditiis praesentium culpa, aperiam quam officiis a consequuntur maxime cum nisi neque corrupti quaerat sed dolore error odit quis, nam voluptatibus provident repudiandae ut? Voluptas beatae fugiat vero culpa quia cum repellat accusamus eos, eaque rerum consectetur eligendi illum, exercitationem, corporis dolorum! Rerum quisquam ipsa libero nostrum at expedita voluptatum omnis vitae, totam non eius!</p>

      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia magni tempore sit perferendis est quibusdam consectetur alias esse assumenda aut aliquid cupiditate, amet impedit similique veritatis aliquam quaerat sint omnis aperiam accusantium quasi excepturi? <br /> Consectetur iure fugiat eius quia at sit ea hic officiis labore eligendi! Earum facere libero dicta, mollitia voluptates ipsum, sequi deserunt quos sunt eos voluptate. Perspiciatis deserunt magnam exercitationem! Accusantium totam sapiente ipsum eveniet iste facilis delectus optio quas. Quam, obcaecati? Placeat consectetur earum ab quasi laborum nisi consequatur sunt soluta eligendi libero provident <br /> eaque ut, aliquid necessitatibus sed molestias? Incidunt nemo consequatur, quidem tempora quae animi esse maxime eos quam officia minima voluptatibus, deserunt vitae! Consequatur deserunt quae pariatur. Consequatur quasi eveniet incidunt cum laudantium vero, pariatur molestias omnis vitae amet asperiores quaerat perspiciatis libero exercitationem fugiat illum dolorum nisi. Obcaecati deserunt necessitatibus ratione veniam eos in? Modi consequatur impedit <br /> blanditiis praesentium culpa, aperiam quam officiis a consequuntur maxime cum nisi neque corrupti quaerat sed dolore error odit quis, nam voluptatibus provident repudiandae ut? Voluptas beatae fugiat vero culpa quia cum repellat accusamus eos, eaque rerum consectetur eligendi illum, exercitationem, corporis dolorum! Rerum quisquam ipsa libero nostrum at expedita voluptatum omnis vitae, totam non eius!</p>

      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia magni tempore sit perferendis est quibusdam consectetur alias esse assumenda aut aliquid cupiditate, amet impedit similique veritatis aliquam quaerat sint omnis aperiam accusantium quasi excepturi? <br /> Consectetur iure fugiat eius quia at sit ea hic officiis labore eligendi! Earum facere libero dicta, mollitia voluptates ipsum, sequi deserunt quos sunt eos voluptate. Perspiciatis deserunt magnam exercitationem! Accusantium totam sapiente ipsum eveniet iste facilis delectus optio quas. Quam, obcaecati? Placeat consectetur earum ab quasi laborum nisi consequatur sunt soluta eligendi libero provident <br /> eaque ut, aliquid necessitatibus sed molestias? Incidunt nemo consequatur, quidem tempora quae animi esse maxime eos quam officia minima voluptatibus, deserunt vitae! Consequatur deserunt quae pariatur. Consequatur quasi eveniet incidunt cum laudantium vero, pariatur molestias omnis vitae amet asperiores quaerat perspiciatis libero exercitationem fugiat illum dolorum nisi. Obcaecati deserunt necessitatibus ratione veniam eos in? Modi consequatur impedit <br /> blanditiis praesentium culpa, aperiam quam officiis a consequuntur maxime cum nisi neque corrupti quaerat sed dolore error odit quis, nam voluptatibus provident repudiandae ut? Voluptas beatae fugiat vero culpa quia cum repellat accusamus eos, eaque rerum consectetur eligendi illum, exercitationem, corporis dolorum! Rerum quisquam ipsa libero nostrum at expedita voluptatum omnis vitae, totam non eius!</p>

      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia magni tempore sit perferendis est quibusdam consectetur alias esse assumenda aut aliquid cupiditate, amet impedit similique veritatis aliquam quaerat sint omnis aperiam accusantium quasi excepturi? <br /> Consectetur iure fugiat eius quia at sit ea hic officiis labore eligendi! Earum facere libero dicta, mollitia voluptates ipsum, sequi deserunt quos sunt eos voluptate. Perspiciatis deserunt magnam exercitationem! Accusantium totam sapiente ipsum eveniet iste facilis delectus optio quas. Quam, obcaecati? Placeat consectetur earum ab quasi laborum nisi consequatur sunt soluta eligendi libero provident <br /> eaque ut, aliquid necessitatibus sed molestias? Incidunt nemo consequatur, quidem tempora quae animi esse maxime eos quam officia minima voluptatibus, deserunt vitae! Consequatur deserunt quae pariatur. Consequatur quasi eveniet incidunt cum laudantium vero, pariatur molestias omnis vitae amet asperiores quaerat perspiciatis libero exercitationem fugiat illum dolorum nisi. Obcaecati deserunt necessitatibus ratione veniam eos in? Modi consequatur impedit <br /> blanditiis praesentium culpa, aperiam quam officiis a consequuntur maxime cum nisi neque corrupti quaerat sed dolore error odit quis, nam voluptatibus provident repudiandae ut? Voluptas beatae fugiat vero culpa quia cum repellat accusamus eos, eaque rerum consectetur eligendi illum, exercitationem, corporis dolorum! Rerum quisquam ipsa libero nostrum at expedita voluptatum omnis vitae, totam non eius!</p>

      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia magni tempore sit perferendis est quibusdam consectetur alias esse assumenda aut aliquid cupiditate, amet impedit similique veritatis aliquam quaerat sint omnis aperiam accusantium quasi excepturi? <br /> Consectetur iure fugiat eius quia at sit ea hic officiis labore eligendi! Earum facere libero dicta, mollitia voluptates ipsum, sequi deserunt quos sunt eos voluptate. Perspiciatis deserunt magnam exercitationem! Accusantium totam sapiente ipsum eveniet iste facilis delectus optio quas. Quam, obcaecati? Placeat consectetur earum ab quasi laborum nisi consequatur sunt soluta eligendi libero provident <br /> eaque ut, aliquid necessitatibus sed molestias? Incidunt nemo consequatur, quidem tempora quae animi esse maxime eos quam officia minima voluptatibus, deserunt vitae! Consequatur deserunt quae pariatur. Consequatur quasi eveniet incidunt cum laudantium vero, pariatur molestias omnis vitae amet asperiores quaerat perspiciatis libero exercitationem fugiat illum dolorum nisi. Obcaecati deserunt necessitatibus ratione veniam eos in? Modi consequatur impedit <br /> blanditiis praesentium culpa, aperiam quam officiis a consequuntur maxime cum nisi neque corrupti quaerat sed dolore error odit quis, nam voluptatibus provident repudiandae ut? Voluptas beatae fugiat vero culpa quia cum repellat accusamus eos, eaque rerum consectetur eligendi illum, exercitationem, corporis dolorum! Rerum quisquam ipsa libero nostrum at expedita voluptatum omnis vitae, totam non eius!</p>

      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia magni tempore sit perferendis est quibusdam consectetur alias esse assumenda aut aliquid cupiditate, amet impedit similique veritatis aliquam quaerat sint omnis aperiam accusantium quasi excepturi? <br /> Consectetur iure fugiat eius quia at sit ea hic officiis labore eligendi! Earum facere libero dicta, mollitia voluptates ipsum, sequi deserunt quos sunt eos voluptate. Perspiciatis deserunt magnam exercitationem! Accusantium totam sapiente ipsum eveniet iste facilis delectus optio quas. Quam, obcaecati? Placeat consectetur earum ab quasi laborum nisi consequatur sunt soluta eligendi libero provident <br /> eaque ut, aliquid necessitatibus sed molestias? Incidunt nemo consequatur, quidem tempora quae animi esse maxime eos quam officia minima voluptatibus, deserunt vitae! Consequatur deserunt quae pariatur. Consequatur quasi eveniet incidunt cum laudantium vero, pariatur molestias omnis vitae amet asperiores quaerat perspiciatis libero exercitationem fugiat illum dolorum nisi. Obcaecati deserunt necessitatibus ratione veniam eos in? Modi consequatur impedit <br /> blanditiis praesentium culpa, aperiam quam officiis a consequuntur maxime cum nisi neque corrupti quaerat sed dolore error odit quis, nam voluptatibus provident repudiandae ut? Voluptas beatae fugiat vero culpa quia cum repellat accusamus eos, eaque rerum consectetur eligendi illum, exercitationem, corporis dolorum! Rerum quisquam ipsa libero nostrum at expedita voluptatum omnis vitae, totam non eius!</p>

      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia magni tempore sit perferendis est quibusdam consectetur alias esse assumenda aut aliquid cupiditate, amet impedit similique veritatis aliquam quaerat sint omnis aperiam accusantium quasi excepturi? <br /> Consectetur iure fugiat eius quia at sit ea hic officiis labore eligendi! Earum facere libero dicta, mollitia voluptates ipsum, sequi deserunt quos sunt eos voluptate. Perspiciatis deserunt magnam exercitationem! Accusantium totam sapiente ipsum eveniet iste facilis delectus optio quas. Quam, obcaecati? Placeat consectetur earum ab quasi laborum nisi consequatur sunt soluta eligendi libero provident <br /> eaque ut, aliquid necessitatibus sed molestias? Incidunt nemo consequatur, quidem tempora quae animi esse maxime eos quam officia minima voluptatibus, deserunt vitae! Consequatur deserunt quae pariatur. Consequatur quasi eveniet incidunt cum laudantium vero, pariatur molestias omnis vitae amet asperiores quaerat perspiciatis libero exercitationem fugiat illum dolorum nisi. Obcaecati deserunt necessitatibus ratione veniam eos in? Modi consequatur impedit <br /> blanditiis praesentium culpa, aperiam quam officiis a consequuntur maxime cum nisi neque corrupti quaerat sed dolore error odit quis, nam voluptatibus provident repudiandae ut? Voluptas beatae fugiat vero culpa quia cum repellat accusamus eos, eaque rerum consectetur eligendi illum, exercitationem, corporis dolorum! Rerum quisquam ipsa libero nostrum at expedita voluptatum omnis vitae, totam non eius!</p>
    </div>
    
  );
}

export default index;